### PR TITLE
Add cmake-based build system

### PR DESCRIPTION
**Pull request by hyviquel**
I followed the behavior of the Makefile, but you should check if the debugging variables of cuda/nvptx RTLs are correctly set.

### CODE REVIEW

**Comment by sfantao** [comment]
Thanks hyviquel,

I'll review this ASAP.

Samuel

**Comment by hyviquel** [comment]
Just update with few cosmetic changes

**Comment by sfantao** [comment]
Hi Herve,

Thanks again for working on this!

I had to tweak a little bit some of the files to make it work in my system. In summary:
- I am using -std=c++11 without the guard for gcc so I could compile this with clang as well;
- Add to pass the CUDA architecture to cuda_add_library so all commands, linker included, get it right;
- Have to explicitly add -lcuda to the cuda plugin link libraries because cmake seems to pass the path to the library and libdl needs lcuda to be specified in the library in order to get that dependency when the plugin is loaded at runtime;
- While matching tmachine, I had to use the regex terminator $ to make sure ppc64le is not matched with ppc64
- All plugins have to be shared libraries.

Below is the diff from your latest commit, give it a try and let me know if it also works in your environment.

Thanks again!
Samuel

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2a955cf..7cc1965 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -33,9 +33,7 @@ if(CUDA_FOUND)
 endif()

 # Allow support for C++11 
-if(CMAKE_COMPILER_IS_GNUCXX)
-    add_definitions(-std=gnu++0x)
-endif()
+add_definitions(-std=c++11)

 if(CMAKE_BUILD_TYPE MATCHES Debug)
     add_definitions(-DOMPTARGET_DEBUG)
diff --git a/DevRTLs/nvptx/CMakeLists.txt b/DevRTLs/nvptx/CMakeLists.txt
index 4864876..15fafff 100644
--- a/DevRTLs/nvptx/CMakeLists.txt
+++ b/DevRTLs/nvptx/CMakeLists.txt
@@ -33,17 +33,17 @@ if(CUDA_FOUND)

     message("Building NVPTX device RTL")

-    # Pass options to NVCC
     if(DEFINED ${OMPTARGET_NVPTX_SM})
-        set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -arch sm_${OMPTARGET_NVPTX_SM})
+        set(CUDA_ARCH -arch sm_${OMPTARGET_NVPTX_SM})
     else()
-        set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -arch sm_35)
+        set(CUDA_ARCH -arch sm_35)
     endif()
-    
+  
     set(BUILD_SHARED_LIBS OFF)
     set(CUDA_SEPARABLE_COMPILATION ON)

-    cuda_add_library(omptarget-nvptx ${cuda_src_files})
+    cuda_add_library(omptarget-nvptx STATIC ${cuda_src_files} 
+        OPTIONS ${CUDA_ARCH})

     target_link_libraries(omptarget-nvptx ${CUDA_LIBRARIES})

diff --git a/RTLs/cuda/CMakeLists.txt b/RTLs/cuda/CMakeLists.txt
index f61f2cf..39fdadd 100644
--- a/RTLs/cuda/CMakeLists.txt
+++ b/RTLs/cuda/CMakeLists.txt
@@ -22,7 +22,7 @@ if(CUDA_FOUND)
     endif()

     add_library(omptarget.rtl.cuda SHARED src/rtl.cpp)
-    target_link_libraries(omptarget.rtl.cuda ${CUDA_LIBRARIES} ${LIBELF_LIBRARIES})
+    target_link_libraries(omptarget.rtl.cuda ${CUDA_LIBRARIES} -lcuda ${LIBELF_LIBRARIES})

 else()

diff --git a/RTLs/ppc64/CMakeLists.txt b/RTLs/ppc64/CMakeLists.txt
index 9e55488..67d1bb7 100644
--- a/RTLs/ppc64/CMakeLists.txt
+++ b/RTLs/ppc64/CMakeLists.txt
@@ -15,7 +15,7 @@ set(tmachine "ppc64")
 set(tmachine_name "PPC64")
 set(tmachine_libname "ppc64")

-if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine})
+if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine}$)

     message("Building " ${tmachine_name} " target RTL")

@@ -24,7 +24,7 @@ if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine})

     add_definitions(-DTARGET_NAME=${tmachine_name})

-    add_library(omptarget.rtl.${tmachine_libname} ../generic-64bit/src/rtl.cpp)
+    add_library(omptarget.rtl.${tmachine_libname} SHARED ../generic-64bit/src/rtl.cpp)
     target_link_libraries(omptarget.rtl.${tmachine_libname}
         ${LIB_FFI_LIBRARIES} ${LIBELF_LIBRARIES}
     )
diff --git a/RTLs/ppc64le/CMakeLists.txt b/RTLs/ppc64le/CMakeLists.txt
index ac02001..a212e64 100644
--- a/RTLs/ppc64le/CMakeLists.txt
+++ b/RTLs/ppc64le/CMakeLists.txt
@@ -15,7 +15,7 @@ set(tmachine "ppc64le")
 set(tmachine_name "PPC64le")
 set(tmachine_libname "ppc64")

-if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine})
+if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine}$)

     message("Building " ${tmachine_name} " target RTL")

@@ -24,7 +24,7 @@ if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine})

     add_definitions(-DTARGET_NAME=${tmachine_name})

-    add_library(omptarget.rtl.${tmachine_libname} ../generic-64bit/src/rtl.cpp)
+    add_library(omptarget.rtl.${tmachine_libname} SHARED ../generic-64bit/src/rtl.cpp)
     target_link_libraries(omptarget.rtl.${tmachine_libname}
         ${LIB_FFI_LIBRARIES} ${LIBELF_LIBRARIES}
     )
diff --git a/RTLs/x86_64/CMakeLists.txt b/RTLs/x86_64/CMakeLists.txt
index 8520ef0..c9a9261 100644
--- a/RTLs/x86_64/CMakeLists.txt
+++ b/RTLs/x86_64/CMakeLists.txt
@@ -15,7 +15,7 @@ set(tmachine "x86_64")
 set(tmachine_name "x86_64")
 set(tmachine_libname "x86_64")

-if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine})
+if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine}$)

     message("Building " ${tmachine_name} " target RTL")

@@ -24,7 +24,7 @@ if(CMAKE_SYSTEM_PROCESSOR MATCHES ${tmachine})

     add_definitions(-DTARGET_NAME=${tmachine_name})

-    add_library(omptarget.rtl.${tmachine_libname} ../generic-64bit/src/rtl.cpp)
+    add_library(omptarget.rtl.${tmachine_libname} SHARED ../generic-64bit/src/rtl.cpp)
     target_link_libraries(omptarget.rtl.${tmachine_libname}
         ${LIB_FFI_LIBRARIES} ${LIBELF_LIBRARIES}
     )
```

**Comment by hyviquel** [comment]
Your patch works fine on my linux (ubuntu 15.04). Just one comment: You should use `cuda` instead of `-lcuda` to respect cmake syntax for linking (the `-l`is automatically added).

I still have error when building `omptarget.rtl.cuda` on OSX because of `-lcuda` and `SHARED` but I will make another push request when I find a workaround.

**Pull request merged**
