### PR TITLE
Implement OMP_DEFAULT_DEVICE

### PR DESCRIPTION
**Pull request by hahnjo**
Or was it meant to be implemented in a different location?

### CODE REVIEW

**Comment by carlobertolli** [comment]
Hi hahnjo

Thanks for this - I think that is appropriate. The only thing is that I would have rather used strtol than atoi.
I did not remember the specific reason, so I had to google it:

http://rus.har.mn/blog/2014-05-19/strtol-error-checking/

What do you think?

Thanks!

-- Carlo

**Comment by hahnjo** [comment]
Hi Carlo,

yes, I will use this function.

Thanks,
Jonas

**Comment by sfantao** [comment]
Hi Jonas,

Yes, one could create a class - say DefaultValues. We also have other env vars like OMP_THREAD_LIMIT that we may want to capture in there, so we can bundle all of them in that class.

About the message, its fine to produce a warning but only in debug mode. 

Thanks!
Samuel

**Comment by hahnjo** [comment]
Updated with static initialization and `strotol`. I tried to catch all corner cases...

In my opinion we should give a hint to the user that the environment variable is invalid. `libomp` does so as well... I have used `DP` in this commit though.

Thanks,
Jonas

**Comment by carlobertolli** [comment]
It sounds reasonable to me to print out an hint, but I think the codebase is not yet prepared to have that in place. Using DP and being able to see it at least in debug mode seems reasonable to me.

Let me try this locally and I will let you know.

Thanks!

-- Carlo

**Comment by carlobertolli** [comment]
This works on my local env and with tests targeting the feature. LGTM.

**Pull request merged**
